import{a as b,S as v,i as n}from"./assets/vendor-Cu43xbyG.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const S="55463829-87ababc408fcd8cb97ff0a765";async function p(r,o=1){return(await b.get("https://pixabay.com/api/",{params:{key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}const m=document.querySelector(".gallery");document.querySelector(".loader");const g=document.querySelector(".load-btn");let q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const o=r.map(e=>`
      <li class="gallery-item">
        <a class="item-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="img-info-wrapper">
          <p class="img-info">Likes: <span class="info-accent">${e.likes}</span></p>
          <p class="img-info">Views: <span class="info-accent">${e.views}</span></p>
          <p class="img-info">Comments: <span class="info-accent">${e.comments}</span></p>
          <p class="img-info">Downloads: <span class="info-accent">${e.downloads}</span></p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",o),q.refresh()}function P(){m.innerHTML=""}function h(){document.querySelector(".loader").classList.add("active")}function L(){document.querySelector(".loader").classList.remove("active")}function M(r){return new Promise(o=>setTimeout(o,r))}function w(){g.classList.add("is-visible")}function c(){g.classList.remove("is-visible")}const f=document.querySelector(".form"),R=document.querySelector(".load-btn");let i=1,u="",d=0;f.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(!o){n.error({message:"Please enter a search query!",position:"topRight"});return}u=o,i=1,P(),c(),h();try{const e=await p(u,i);if(d=e.totalHits,await M(500),e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(e.hits);const a=Math.ceil(d/15);i<a?w():(c(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),f.reset()}});async function $(){i+=1,c(),h();try{const r=await p(u,i);y(r.hits);const o=Math.ceil(d/15);i<o?w():(c(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const e=document.querySelector(".gallery-item");if(e){const a=e.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}}R.addEventListener("click",$);
//# sourceMappingURL=index.js.map
